version: '3.5'

services:
  auth_db:
    container_name: auth_db
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bQ5UroNM9PqslBs}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-auth_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data # Lưu trữ dữ liệu PostgreSQL
    networks:
      - app_network
    restart: on-failure

volumes:
  auth_db_data: # Volume để lưu trữ dữ liệu PostgreSQL

networks:
  app_network:
    driver: bridge
